version: '3.4'

services:
  testbackend:
    image: testbackend
    build: .
    environment:
      NODE_ENV: development 
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
      
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongodumps/dump/hospitalDump:/hospitalDump
     
